version : 2
jobs:
  build:
    working_directory : ~/hackernews_android_code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androdDependencies
      - run:
          name: Running Tests
          command: ./gradlew lint tests
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test_results
      - run:
          name: Building APK
          command: ./gradlew --no-daemon --stacktrace assembleDebug
      - store_artifacts:
          path: app/build/apk